### ISSUE TITLE
Difference from net.ltgt.apt?

### ISSUE THREAD

**Issue by tbroyer** [palantir/gradle-processors#1]
Hi,

I created the [`net.ltgt.apt`](https://plugins.gradle.org/plugin/net.ltgt.apt) a few months before your plugin, and was wondering what differences there are between them.

**Comment by cjp39** [comment]
Hi Thomas,

I found your plugin when open-sourcing this one (race condition). Had it been available when I first wrote ours, I'd have used it. However, having already written ours, there are a few key differences I didn't think it would be appropriate to merge in.

# We disable javac's regular annotation processing, and set the annotation processor path instead. That means annotation processors included via 'compile' will stop working, to ensure the behaviour matches Eclipse.
# We change Eclipse's default destination for generated code to one that's visible in the IDE
# We own the setup of IDEA's root project to enable annotation processing with no manual steps. At the moment, this is done by saying the annotation processor path to match the compilation path, but I'd like to fix that in future to match the other two.

I may also try and figure out a way to include Eclipse plugins in processor jars in future, as transparent refactoring support would be neat.

Hope that clears things up, and thanks for reaching out!
Chris

**Comment by tbroyer** [comment]
Hmm, `net.ltgt.apt` also uses the `-processorpath` (even if the `apt` configuration is empty) and configures Eclipse (although I must admit I don't think I ever actually tried it) and IDEA (with something really similar, judging by our plugins' code; the "manual step" is needed if you don't use the `*.ipr` format in IDEA but instead use the `.idea/` workspace layout). If you look at my commit history, you'll note that I initially configured the processor path in IDEA too, but finally changed my mind (see tbroyer/gradle-apt-plugin@0ca5ea1120ce785f2f33c01af0be1b878345487c). I also preferred reconfiguring IDEA to no longer ignore `build/generated/sources` rather than use different output directories between the IDE and the Gradle build (it'd also force you to add those folders to your `.gitignore`).

Re. the various options and whether they're too "complex", I think it depends where you come from:
 * `compileOnly` can be seen as similar to `provided` from Android and webapps, but is really only added to the compile classpath (`provided` in webapps is only excluded from the WAR packaging, but is included in the test classpath for instance, both compile-time and runtime). This is generally where you put annotations that are referenced in code but don't need to be shipped with your app; e.g. annotations that trigger annotation processors. The `compileOnly` configuration extends the `compile` configuration though, so beware of transitive dependencies and version conflict mediation/resolution.
* `apt` doesn't extend `compile` or `compileOnly`, specifically to avoid dependency issues, such as an annotation processor depending on ASM 3 (this is a mistake to begin with, but that's a story for another day) whereas your code depends on ASM 5: you don't want to bring ASM 5 in your processor path. That could also happen with, say, Guava, where an annotation processor can depend on an oldish version of Guava and make use of a feature that has since been deprecated and then removed; if your code depends on a recent version of Guava and the configurations extended each other, you'd end up with the recent Guava in the processor path, breaking your annotation processor. Finally, it also allows segregating annotation processors you don't want to run (maybe because you don't even know they exist) by not putting in the `apt` configuration: real-life example is Closure Templates depending on ANTLR, and ANTLR actually bundles an annotation processor, and at some point it started displaying warnings: https://github.com/antlr/antlr4/issues/487; with `net.ltgt.apt`, ANTLR is not in the processor path, so its annotation processor is never run. This is also the reason for test-only annotation processors: not to mix "paths".

**Comment by cjp39** [comment]
Ah, your README totally confused me about the IDEA setup :/ Perhaps there' a way to rewrite that so it's clearer? Perhaps a section title of "IntelliJ" that start with "Ideally use gradle idea, then there are no further steps, but if you're using IDEA's gradle plugin, then you'll have to..."?

I see your point about apt/compileOnly being more flexible, but I want instructions that are "a, b, c", not "a, try b, maybe c, d". That means annotation processors go in "processor", everything else goes in "compile". Having to worry about compileOnly as well...I'd rather leave that to a separate plugin.
