### ISSUE TITLE
Plugin cannot run under Java7

### ISSUE THREAD

**Issue by kadaan** [palantir/gradle-processors#17]
The plugin is built with Java8, so it cannot be used in Java7.  As far as I can tell, there is no reason that this project needs to be built with Java8.  Please release a new version which is built with Java7.

**Comment by cjp39** [comment]
Your fix released as [v1.1.2](https://github.com/palantir/gradle-processors/releases/tag/v1.1.2). Let me know if that didn't fix things for you!
