### ISSUE TITLE
Javadoc classpath does not contain processor library

### ISSUE THREAD

**Issue by markelliot** [palantir/gradle-processors#19]
For Immutables, at least, when I generate Javadoc for classes that are annotated with Immutables annotations, I get warnings like this:

    javadoc: warning - Class Value.Immutable not found.

**Comment by markelliot** [comment]
It seems as though a sufficient fix for this in my own build script is:

    javadoc {
        classpath = sourceSets.main.compileClasspath + configurations.processor
    }

**Comment by cjp39** [comment]
Fix released as [v1.1.3](https://github.com/palantir/gradle-processors/releases/tag/v1.1.3). Thanks @markelliot!
