### ISSUE TITLE
The plus(Iterable<FileCollection>) method and using the '+' operator in conjunction with an Iterable<FileCollection> object have been deprecated

### ISSUE THREAD

**Issue by michael-yx-wu** [palantir/gradle-processors#23]
The following deprecation warning appears for me while using Gradle 2.10.

`The plus(Iterable<FileCollection>) method and using the '+' operator in conjunction with an Iterable<FileCollection> object have been deprecated and are scheduled to be removed in 3.0.  Please use the plus(FileCollection) method or the '+' operator with a FileCollection object instead.`

**Comment by cjp39** [comment]
Which version of the plugin are you using? This bug should have been fixed in 1.1.1, though I've just noticed that we still refer to v1.1 in the README.

**Comment by michael-yx-wu** [comment]
Looks like we're still on 1.1. I'll upgrade us to 1.1.1. Thanks :)

**Comment by cjp39** [comment]
You may want to go with at least 1.1.2 if you're still on Java 7.
