### ISSUE TITLE
Specify process order

### ISSUE THREAD

**Issue by mvanrobaeys** [palantir/gradle-processors#32]
I have 2 annotation processors, 1 needs to be executed before the other. 

How would you be able to perform this task with the plugin?

**Comment by chrisalice** [comment]
Why the ordering constraint? The output of one annotation processor is not compiled before the second is run, so order is very unlikely to have an effect. Instead, after the first round of code generation, javac compiled all the generated source and reruns every annotation processor again for a second round. It's up to the annotation processors to spot the new types on the second round. All of which is to say, you may need to raise a bug against one of the annotation processors you're using.
