### ISSUE TITLE
generated_src directory isn't marked correctly in IntelliJ

### ISSUE THREAD

**Issue by a-k-g** [palantir/gradle-processors#33]
In version 1.2.1 with Gradle 2.12 the generated_src directory doesn't get marked as a source root in IntelliJ. It seems to work fine if I just change my version for org.inferred.processors to 1.1.6.

**Comment by nmiyake** [comment]
@chrisalice , this is also fixed by #35 so should be able to close this

**Comment by chrisalice** [comment]
ah, you got the autoclose magic wrong in your PR for this one 😉

**Comment by chrisalice** [comment]
This is fixed in [v1.2.2](https://github.com/palantir/gradle-processors/releases/tag/1.2.2).
