### ISSUE TITLE
Does work in IntelliJ

### ISSUE THREAD

**Issue by justinuang** [palantir/gradle-processors#34]
To get it to work, I have to first:

    1. Go to Build, Execution, Deployment > Compiler > Annotation Processors
        Settings should be: Enable annotation processing

    2. Module Content Root, change production -> generated_src and test -> generated_testSrc

**Comment by uschi2000** [comment]
Works out of the box for me (IDEA 15 and 2016) . Did you apply the plugin to the root project?

**Comment by justinuang** [comment]
Ah, I forgot that. Unfortunately, I can't figure out how to roll back my
IntelliJ to repro the issue, but I'll close the issue.

**Comment by justinuang** [comment]
Thanks! =)

**Comment by chrisalice** [comment]
Note that this is no longer necessary as of [v1.2.2](https://github.com/palantir/gradle-processors/releases/tag/1.2.2).
