### ISSUE TITLE
Annotation processors not running consistently in Eclipse

### ISSUE THREAD

**Issue by alicederyn** [palantir/gradle-processors#5]
When we run `gradle eclipse` on a specific project, and import into Eclipse, annotation processors do not appear to run. Only known workaround is to disable and reenable annotation processing for that project.

**Comment by cjp39** [comment]
This may be due to Eclipse entering "batch" mode once a specific number of files are reached; this mode has serious bugs with annotation processing. Workaround is to increase the batch size, but I'm having trouble tracking down how to do that. More as I figure it out.

**Comment by cjp39** [comment]
The specific workaround I was remembering is documented at https://gerrit-review.googlesource.com/#/c/70494/3/Documentation/dev-eclipse.txt, but unfortunately it doesn't solve this issue.

**Comment by alicederyn** [comment]
Cannot reproduce
