### ISSUE TITLE
Ignoring Immutables not working with latest Baseline findbugs

### ISSUE THREAD

**Issue by griechel** [palantir/gradle-processors#50]
Baseline version 0.9.1 and above includes an SLF4J findbugs plugin (https://github.com/KengoTODA/findbugs-slf4j), and running findbugsMain with this new plugin will fail with some products, because of a failure to find some Immutable classes.

I've opened a PR to remove this code in gradle-processors #49.The most recent version of Immutables (2.3.7) seems to work much better with findbugs, and products that I've tested which use this updated version of gradle-processors in combination with upgrading Immutables seem to be stable.

Alternatively, we can improve the logic in gradle-processors to be more aggressive when ignoring processors, although it's still unclear to me why the current implementation stopped working for me.

**Comment by chrisalice** [comment]
The problem is that we're removing the source entirely rather than ignoring it. More recent versions of FindBugs have the option to ignore generated code properly, I believe, rather than needing this workaround — can we check the FindBugs version and execute the workaround only for older versions?

**Comment by chrisalice** [comment]
This should now be fixed as of [v1.2.10](https://github.com/palantir/gradle-processors/releases/tag/v1.2.10)
