### ISSUE TITLE
Intellij 2016.3 Caused by: groovy.lang.GroovyRuntimeException: replaceNode() can only be used to replace a single node.

### ISSUE THREAD

**Issue by domcc** [palantir/gradle-processors#51]
Hi,

When importing a gradle project into Intellij 2013.3 i get the error
"Caused by: groovy.lang.GroovyRuntimeException: replaceNode() can only be used to replace a single node."

Looks at the code it looks like line 202 is at fault:
`compilerConfiguration.annotationProcessing.replaceNode{`
I'm guessing IntelliJ 2016.3 has changed so a newly created project does not contain `<annotationProcessing>`
`</annotationProcessing>`
which means compilerConfiguration.annotationProcessing has a count of 0?
If i manually add that to the .idea\compiler.xml file then the loading of the gradle project works.

**Comment by jophde** [comment]
Also seeing this issue and the temporary fix worked for me.

**Comment by chrisalice** [comment]
This should now be fixed in [v1.2.5](https://github.com/palantir/gradle-processors/releases/tag/v1.2.5). Thanks @jhoch-palantir!
