### ISSUE TITLE
org.eclipse.jdt.apt.genSrcDir sets to bin/generated/java in eclipse apt prefs since 1.2.4

### ISSUE THREAD

**Issue by qinfchen** [palantir/gradle-processors#56]
Since 1.2.4, `org.eclipse.jdt.apt.genSrcDir` gets set to `bin/generated/java` instead of `generated_src` in org.eclipse.jdt.apt.core.prefs. This breaks the Eclipse workflow and immutable classes no longer get generated on clean projects.

**Comment by chrisalice** [comment]
Thanks, Qinfeng! This should be fixed in 1.2.8.

**Comment by qinfchen** [comment]
sweet! thanks for the fast fix!
