### ISSUE TITLE
Bad generated_src folder in IntelliJ

### ISSUE THREAD

**Issue by tkruse** [palantir/gradle-processors#58]
Following up on my report at https://github.com/google/FreeBuilder/issues/245
I tried again. To reproduce, try importing and building my dummy project at 
https://github.com/tkruse/beantest/tree/inferred_plugin

Do **NOT** use the master branch, I added the inferred plugin only in the inferred_plugin branch.

When importing the project in IntelliJ 2016.3.4, then building, I get the following structure:

* beantest
  * generated_src [main]
    * generated_src
      * com ...

which causes all generated classes to be inside package generated_src.com... instead of com...

Also I am slightly annoyed at this being inside the module root, rather than the build folder, and not being cleaned by gradle clean.
Also this ends up having both generated .java and .class files inside build/classes, which is unclean.

The ideal state for me would be for IntelliJ to mirror gradle's behavior, for the generated java sources to be in build/generated_src, and for build/classes only containing .class files.

Feel free to make a PR on my github repo if simple changes to my projects build.gradle can achieve this.

Sorry if my github project example is not minimal, if it would help you a lot, I can reduce it to be minimal.

**Comment by chrisalice** [comment]
Reproduced, thanks for the sample. Apparently IntelliJ has redefined what "Store generated sources relative to module content root" means. Fantastic. Will investigate further.

**Comment by tkruse** [comment]
This is the 'solution' they gave me for now: https://github.com/tkruse/beantest/blob/raw/README.md (bottom).

**Comment by chrisalice** [comment]
Re your ideal state: unfortunately, if you try to put generated sources under build/, IntelliJ will refuse to recognise them. We did try that originally.

**Comment by tkruse** [comment]
Well, in their solution, they suggest to me to make build/classes a source folder. Also might be good to compare to maven support. There should be a valid pom.xml in the project as well.

**Comment by chrisalice** [comment]
Ah, apparently we _can_ do that in recent versions of IntelliJ. Assuming we want to break everyone still on an old version.

**Comment by chrisalice** [comment]
Could you give [v1.2.9-rc2](https://github.com/palantir/gradle-processors/releases/tag/v1.2.9-rc2) a whirl?

**Comment by chrisalice** [comment]
Also, if you could get in touch with me at Chris.Purcell.39@gmail.com, I'm curious what some of your beantest README notes refer to, especially "List and Map have nice Builder methods to add instead of setting, but those can be buggy"

**Comment by tkruse** [comment]
Hi Chris, 1.2.9-rc2 fixes the problem with the additional folder in the hierarchy for me.

Regarding my scribbles, I cannot remember what I was thinking at the time. It does not make much sense to me now. Maybe I was talking about Nullness annotations, maybe something else. If I had detected a reproducible bug, I would have created a github issue, so that wasn't it.

I can make a commit cleaning up those comments and removing what I cannot justify anymore.

**Comment by chrisalice** [comment]
This should be fixed in [v1.2.9](https://github.com/palantir/gradle-processors/releases/tag/v1.2.9). Thanks, Thibault!
