### ISSUE TITLE
IntelliJ thinks our modules have cycles  

### ISSUE THREAD

**Issue by leeavital** [palantir/gradle-processors#65]
We ran into this issue when upgrading from 1.2.8 to 1.2.10

we have two modules: impl and  testing-utils with the following dependencies:

testCompile(impl) depends on compile(testing-utils)
compile(testing-utils) dependsOn compile(impl) 
testCompile(impl) dependsOn compile(impl)

Both packages have annotations to be processed.

Gradle can build this fine, but intellij mistakenly thinks there is a cycle between impl and testing-utils

**Comment by chrisalice** [comment]
I'm not sure how we regressed on this?

**Comment by chrisalice** [comment]
@leeavital Could you try gradle-processors v1.2.12-rc2 and see if it fixes this regression?

**Comment by leeavital** [comment]
@chrisalice worked like a charm! Thanks for the quick fix.
