### ISSUE TITLE
Inverse of #58

### ISSUE THREAD

**Issue by henryptung** [palantir/gradle-processors#66]
I'm not sure why, but I'm getting bad behavior out of the fix for #58. I don't think I have the "rogue content root" problem observed there, and I think that's in turn causing the fix to break for me.

![image](https://cloud.githubusercontent.com/assets/1700335/25417404/dae968f4-2a11-11e7-93a8-34f01f6173aa.png)

[Here's a sample repo illustrating the problem.](https://github.com/henryptung/test-project)

IntelliJ version information:
```
IntelliJ IDEA 2016.3.3
Build #IC-163.11103.6, built on January 16, 2017
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by henryptung** [comment]
@tkruse Can you reupload your test case? I'm trying to find a common fix for both cases that won't break mine, but I can't test your use case without a sample.

**Comment by henryptung** [comment]
@chrisalice It seems like subdirectory projects might break now with the `./gradlew idea`, open the `.ipr` file workflow. The root directory project works, but that's only because IntelliJ seems to cap the `../` traversal at the project root directory. All subdirectories have their `generated_[test]Src` directories displaced three levels up.

More generally, should IntelliJ even be aware of the annotation processors when it controls Gradle? The annotation processors are hooked into and invoked by Gradle in that case; I'm not sure IntelliJ should be doing the same on its own, since it builds via Gradle anyway. I'm not sure having IntelliJ manage Gradle is well-supported anyway; IIRC, I've never had success with that model on any non-trivial project, and I think most plugins target support for Gradle to generate good IntelliJ projects, not the other way around.

**Comment by tkruse** [comment]
Next weekend I may come back. Before then, no

**Comment by henryptung** [comment]
@chrisalice Any update on this? I think the latest plugin version is still breaking IntelliJ; for the moment, I've downgraded to v1.2.8 as a workaround on all my projects, but that's not very ideal.

**Comment by chrisalice** [comment]
Sorry, been off for surgery, should pick this up soon

**Comment by chrisalice** [comment]
Bug confirmed. I'll try other options and make a PR.
