### ISSUE TITLE
Provide ability to specify Processors

### ISSUE THREAD

**Issue by tkruse** [palantir/gradle-processors#69]
Not sure if this is possible in any other way. I was looking to specify a processor as in 
https://github.com/xebia-france/selma/issues/125 , specifically
```
<processors>
      <processor>lombok.launch.AnnotationProcessorHider$AnnotationProcessor</processor>                   
      <processor>fr.xebia.extras.selma.codegen.MapperProcessor</processor>
</processors>
```

**Comment by chrisalice** [comment]
That's going to be quite a lot of work and maintenance. Why is automatic discovery not working for you in this case?

**Comment by chrisalice** [comment]
Ah, sorry, your link provides the answer. There's unfortunately no way to set this up in Eclipse and IntelliJ, and it's complicated in Gradle. Totally outside the scope of this plugin, I'm afraid :(

You may have better luck getting Selma to support this if you use a more spec-conformant library than Lombok, as Java is specifically designed to allow conformant annotation processors to interact safely without forcing an ordering via compilation hacks.

**Comment by tkruse** [comment]
thanks for the detailed answer. Sadly I do not understand enough about the issue, but it seems that lombok has been changed to allow some chaining, so probably selma could be changed to work without defining processor order. However, I have no idea how to explain it to them: https://github.com/xebia-france/selma/issues/168

**Comment by chrisalice** [comment]
I guess, point them towards https://github.com/mapstruct/mapstruct/pull/1042 ?
