### ISSUE TITLE
Intellji 2017.3.1 no longer generates Immutable classes to `generated_src`

### ISSUE THREAD

**Issue by qinfchen** [palantir/gradle-processors#77]

**Comment by dwyand** [comment]
+1

**Comment by schlosna** [comment]
Related https://youtrack.jetbrains.com/issue/IDEA-183773

**Comment by bkrieger** [comment]
Looks like this was being tracked in https://youtrack.jetbrains.com/issue/IDEA-183336, but they say it's fixed in the latest build.

**Comment by chrisalice** [comment]
Thanks Brandon, and everyone else who looked into this! I'll leave the issue open for a while so others can find it easily

**Comment by qinfchen** [comment]
Upgraded to 2017.3.2 and verified that this is fixed.
