### ISSUE TITLE
Plugin should appear under com.palantir.gradle namespace (rather than org.inferred)

### ISSUE THREAD

**Issue by punya** [palantir/gradle-processors#8]

**Comment by cjp39** [comment]
Working as intended. `org.inferred` is an umbrella namespace for open-source Java 7 annotation processor–related libraries; see for instance http://inferred.org/freebuilder, which is maintained by Google.

**Comment by jmcampanini** [comment]
can we re-open this issue? i'm not entirely sure if it's working as intended. i can't find where `org.inferred` is used as an umbrella namespace. i've looked in the following places:

- [maven central search](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.inferred%22)
- [github code search](https://github.com/search?l=maven-pom&q=%22org.inferred%22&ref=searchresults&type=Code&utf8=✓)

it seems like the only place it's actually used as the namespace are the project you mention and this project.
